import gsap from 'gsap'
import Observer from 'gsap/dist/Observer'
import ScrollToPlugin from 'gsap/dist/ScrollToPlugin'
import ScrollTrigger from 'gsap/dist/ScrollTrigger'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'

gsap.registerPlugin(ScrollTrigger);
gsap.registerPlugin(ScrollToPlugin);
gsap.registerPlugin(Observer);

export default function ScrollExample() {


  useEffect(() => {

let sections = document.querySelectorAll("section"),
  images = document.querySelectorAll(".bg"),
  headings = gsap.utils.toArray(".section-heading"),
  outerWrappers = gsap.utils.toArray(".outer"),
  innerWrappers = gsap.utils.toArray(".inner"),
  currentIndex = -1,
  wrap = gsap.utils.wrap(0, sections.length - 1),
  animating: boolean;

gsap.set(outerWrappers, { yPercent: 100 });
gsap.set(innerWrappers, { yPercent: -100 });

    function gotoSection(index: number, direction: number) {
    index = wrap(index); // make sure it's valid
    animating = true;
    let fromTop = direction === -1,
        dFactor = fromTop ? -1 : 1,
        tl = gsap.timeline({
            defaults: { duration: 1.25, ease: "power1.inOut" },
            onComplete: () => animating = false
        });
    if (currentIndex >= 0) {
        // The first time this function runs, current is -1
        gsap.set(sections[currentIndex], { zIndex: 0 });
        tl.to(images[currentIndex], { yPercent: -15 * dFactor })
        .set(sections[currentIndex], { autoAlpha: 0 });
    }
    gsap.set(sections[index], { autoAlpha: 1, zIndex: 1 });
    tl.fromTo([outerWrappers[index], innerWrappers[index]], { 
        yPercent: i => i ? -100 * dFactor : 100 * dFactor
        }, { 
        yPercent: 0 
        }, 0)
        .fromTo(images[index], { yPercent: 15 * dFactor }, { yPercent: 0 }, 0)

    currentIndex = index;
    }

    Observer.create({
        type: "wheel,touch,pointer",
        wheelSpeed: -1,
        onDown: () => !animating && gotoSection(currentIndex - 1, -1),
        onUp: () => !animating && gotoSection(currentIndex + 1, 1),
        tolerance: 10,
        preventDefault: true
    });

gotoSection(0, 1);
  }, [])


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <section className="first">
  <div className="outer">
    <div className="inner">
      <div className="bg one">
        <h2 className="section-auto">Scroll down</h2>
      </div>
    </div>
  </div>

</section>
<section className="second">
  <div className="outer">
    <div className="inner">
      <div className="bg">
        <h2 className="section-heading">Animated with GSAP</h2>
      </div>
    </div>
  </div>
</section>
<section className="third">
  <div className="outer">
    <div className="inner">
      <div className="bg">
        <h2 className="section-heading">GreenSock</h2>
      </div>
    </div>
  </div>
</section>
<section className="fourth">
  <div className="outer">
    <div className="inner">
      <div className="bg">
        <h2 className="section-heading">Animation platform</h2>
      </div>
    </div>
  </div>
</section>
<section className="fifth">
  <div className="outer">
    <div className="inner">
      <div className="bg">
        <h2 className="section-heading">Keep scrolling</h2>
      </div>
    </div>
  </div>
</section>
      </main>

    </div>
  )
}
